title: JitLab Connect
description: Report to the Jira about updates from GitLab
show_downloads: true
theme: jekyll-theme-cayman
github:
  shop_url: https://marketplace.atlassian.com/1218423
  shop_text: Get it now
  copyright: © 2018 JitLab Connect
